name: kem
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^4.0.0
  permission_handler: ^11.0.0
  camera: ^0.10.5+9
  location: ^5.0.3
  device_info_plus: ^9.1.0
  http: ^1.1.0
  flutter_background_service: ^5.0.1
  flutter_background_service_android: ^6.3.0
  path_provider: ^2.1.1  # IMPORTANT: Added for audio file storage
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_local_notifications: ^17.2.1
  socket_io_client: ^3.1.2
  uuid: ^4.5.1
  geolocator: ^14.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true